---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - chore
      - github-actions
    commit-message:
      prefix: "chore(gh):"
      include:
        - dependency-name
        - new-version
      separator: " "
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - chore
      - dependencies
    commit-message:
      prefix: "chore(deps):"
      include:
        - dependency-name
        - new-version
      separator: " "
