---
version: "2"

output:
  formats:
    text:
      path: stdout

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    errcheck:
      exclude-functions:
        - github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set
        - fmt:.*
        - io:Close
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # TODO: Setting temporary exclusions for specific linters.
      - linters:
          - errcheck
        text: Error return value of `d.Set` is not checked
      - linters:
          - revive
        text: 'redefines-builtin-id: redefinition of the built-in'
      - linters:
          - staticcheck
        text: 'QF1003: could use tagged switch on newNum'
      - linters:
          - staticcheck
        text: 'QF1004: could use strings.ReplaceAll instead'
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
